=== ardilla1991/rental/resource/equipmentsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/equipmentsSchema" 
xmlns:tns="http://www.example.org/equipmentsSchema" 
elementFormDefault="qualified">
	<xs:element name="equipments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:equipment" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipment" type="tns:EquipmentType" abstract="true"></xs:element>
	<xs:element name="bycicle" type="tns:Bycicle" substitutionGroup="tns:equipment"></xs:element>
	<xs:element name="skate" type="tns:Skate" substitutionGroup="tns:equipment"></xs:element>
	<xs:complexType name="EquipmentType">
		<xs:sequence>
			<xs:element name="price" type="xs:double" />
			<xs:element name="weight" type="xs:double" />
			<xs:element name="width" type="xs:double" />
			<xs:element name="height" type="xs:double" />
			<xs:element name="category" type="tns:Category" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Bycicle">
		<xs:complexContent>
			<xs:extension base="tns:EquipmentType">
				<xs:sequence>
					<xs:element name="count-speed-mode" type="xs:int"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Skate">
		<xs:complexContent>
			<xs:extension base="tns:EquipmentType">
				<xs:sequence>
					<xs:element name="size" type="xs:int"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="Category">
		<xs:restriction base="xs:string">
			<xs:enumeration value="adult"></xs:enumeration>
			<xs:enumeration value="child"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ardilla1991/rental/resource/equipments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<equipments
xmlns="http://www.example.org/equipmentsSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/equipmentsSchema equipmentsSchema.xsd"
>
	<bycicle>
		<price>4.5</price>
		<weight>7.9</weight>
		<width>3</width>
		<height>1</height>
		<category>adult</category>
		<count-speed-mode>20</count-speed-mode>
	</bycicle>
	<bycicle>
		<price>4.1</price>
		<weight>7.3</weight>
		<width>2</width>
		<height>1.1</height>
		<category>child</category>
		<count-speed-mode>3</count-speed-mode>
	</bycicle>
	<skate>
		<price>2</price>
		<weight>0.2</weight>
		<width>0.45</width>
		<height>0.15</height>
		<category>child</category>
		<size>36</size>
	</skate>
	<skate>
		<price>2.3</price>
		<weight>0.7</weight>
		<width>0.5</width>
		<height>0.2</height>
		<category>adult</category>
		<size>39</size>
	</skate>
</equipments>
